site_name:  Chopin
repo_url: https://github.com/pstfni/chopin
repo_name: pstfni/chopin

nav:
  - Introduction:
    - "index.md"
    - "getting_started.md"
  - Guide:
    - "🤖 Compose a playlist":
      - "guide/compose.md"
      - "guide/sources.md"
    - "guide/queue.md"
    - "guide/shuffle.md"
    - "guide/backup_and_restore.md"
  - Reference:
    - "reference/index.md"
    - "reference/entrypoints.md"
    - "reference/managers.md"
    - "reference/client.md"
    - "reference/schemas.md"
    - "reference/tools.md"

theme:
  name: "material"
  custom_dir: .docs_theme/
  icon:
    logo: material/library
    repo: fontawesome/brands/github
    admonition:
      tip: material/music-note-plus
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono


markdown_extensions:
    - tables
    - admonition
    - abbr
    - footnotes
    - md_in_html
    - attr_list
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.arithmatex:
        generic: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python

watch:
  - chopin/managers/
  - chopin/schemas/
  - chopin/entrypoints/
  - .docs_theme/assets/

extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/termynal.css

extra_javascript:
  - assets/js/termynal.js
  - assets/js/custom.js
