exclude = ['.venv']
line-length = 120

[lint]
ignore = ["N805", "B008"]
select = ["F", "E", "W", "I", "N", "D", "UP", "B", "PERF", "RUF"]
fixable = ["ALL"]

[lint.per-file-ignores]
"**/__init__.py" = ['F401']
"**/tests/**" = ["S", "D", "N"]

[lint.pydocstyle]
convention = "google"
